version: '3'
services:
  app:
    build: .
    depends_on:
      - db 
    entrypoint: "./wait-for-it.sh db npm start"
  db:
    image: postgres:12.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
